name: InRoomAirFilterScaleUp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - matplotlib-inline
  - plotly
  - openpyxl
  - xlrd
  - country_converter
  - uncertainties
  - jupyter
  - notebook
  - nbconvert
  - nbformat
  - ipykernel
  - ipywidgets
  - tqdm
  - pip
